/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedFindRouteImport } from './routes/_authenticated/find'
import { Route as AuthenticatedPlayersIdRouteImport } from './routes/_authenticated/players.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/_authenticated/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/_authenticated/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFindRoute = AuthenticatedFindRouteImport.update({
  id: '/_authenticated/find',
  path: '/find',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlayersIdRoute = AuthenticatedPlayersIdRouteImport.update({
  id: '/_authenticated/players/$id',
  path: '/players/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/find': typeof AuthenticatedFindRoute
  '/home': typeof AuthenticatedHomeRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/players/$id': typeof AuthenticatedPlayersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/find': typeof AuthenticatedFindRoute
  '/home': typeof AuthenticatedHomeRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/players/$id': typeof AuthenticatedPlayersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/find': typeof AuthenticatedFindRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/players/$id': typeof AuthenticatedPlayersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/find' | '/home' | '/leaderboard' | '/players/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/find' | '/home' | '/leaderboard' | '/players/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/find'
    | '/_authenticated/home'
    | '/_authenticated/leaderboard'
    | '/_authenticated/players/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedFindRoute: typeof AuthenticatedFindRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedPlayersIdRoute: typeof AuthenticatedPlayersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/find': {
      id: '/_authenticated/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof AuthenticatedFindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/players/$id': {
      id: '/_authenticated/players/$id'
      path: '/players/$id'
      fullPath: '/players/$id'
      preLoaderRoute: typeof AuthenticatedPlayersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedFindRoute: AuthenticatedFindRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedPlayersIdRoute: AuthenticatedPlayersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
